<?php

namespace Database\Seeders;

use App\Models\Customer;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CustomersSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 */
	public function run(): void
	{
		Customer::truncate();

		$customers = [
			[
				'id' => 1,
				'name' => 'Jimmie L. Bertrand',
				'service_location' => null,
				'geo_location' => null,
				'phone_number' => null,
				'house_number' => 'Hussy',
				'street' => 'Fiduciary',
				'address' => null,
				'email' => null,
				'email_verified_at' => null,
				'pin' => null,
				'remember_token' => null,
				'verified_customer' => 0,
				'created_at' => '2023-03-29 08:55:26',
				'updated_at' => '2023-03-29 08:55:26',
			],
			[
				"id" => 2,
				"name" => "Tammie R. Beach",
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "033333",
				"house_number" => "Adios",
				"street" => "Stubborn",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 1,
				"created_at" => "2023-03-29 08:56:43",
				"updated_at" => "2023-03-29 08:56:59",
			],
			[
				"id" => 3,
				"name" => "Julia H. Cotton",
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "03310215272",
				"house_number" => "Arvin",
				"street" => "Serving",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 1,
				"created_at" => "2023-03-29 09:00:42",
				"updated_at" => "2023-03-29 09:00:47",
			],
			[
				"id" => 4,
				"name" => "James A. Griffin",
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "000",
				"house_number" => "artful",
				"street" => "Studio",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 1,
				"created_at" => "2023-03-30 07:00:39",
				"updated_at" => "2023-03-30 07:00:43",
			],
			[
				"id" => 5,
				"name" => "Cheryl S. Moeller",
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "03310215227",
				"house_number" => "Still",
				"street" => "Goodrich",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 1,
				"created_at" => "2023-03-31 05:54:05",
				"updated_at" => "2023-03-31 05:54:13",
			],
			[
				"id" => 6,
				"name" => "Felipe S. Burge",
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "6685642244",
				"house_number" => "It8f",
				"street" => "F7rf7",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 1,
				"created_at" => "2023-03-31 09:02:40",
				"updated_at" => "2023-03-31 09:02:47",
			],
			[
				"id" => 7,
				"name" => "Guadalupe S. Christian",
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "0331021582",
				"house_number" => "At oo",
				"street" => "Studios",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 1,
				"created_at" => "2023-04-03 03:33:07",
				"updated_at" => "2023-04-03 03:33:12",
			],
			[
				"id" => 8,
				"name" => "Mary A. Christenson",
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "08854213534",
				"house_number" => "Atrium",
				"street" => "Setting",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 1,
				"created_at" => "2023-04-04 03:34:45",
				"updated_at" => "2023-04-04 03:35:02",
			],
			[
				"id" => 9,
				"name" => "Helen L. Mahon",
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "03310215277",
				"house_number" => "Scrub0",
				"street" => "Arturo",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 1,
				"created_at" => "2023-04-04 03:44:36",
				"updated_at" => "2023-04-04 03:45:55",
			],
			[
				"id" => 10,
				"name" => "Fred I. Cordova",
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "5656598988",
				"house_number" => "4k",
				"street" => "He 46leyrulto",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 0,
				"created_at" => "2023-04-06 07:40:54",
				"updated_at" => "2023-04-06 07:40:54",
			],
			[
				"id" => 11,
				"name" => "Rena R. Sells",
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "952396522",
				"house_number" => "6ynhji",
				"street" => "Bkk",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 1,
				"created_at" => "2023-04-11 07:16:25",
				"updated_at" => "2023-04-11 07:16:38",
			],
			[
				"id" => 12,
				"name" => "Danyelle W. Yowell",
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "555555",
				"house_number" => "Uuyu",
				"street" => "Ghh",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 0,
				"created_at" => "2023-05-10 04:59:17",
				"updated_at" => "2023-05-10 04:59:17",
			],
			[
				"id" => 13,
				"name" => NULL,
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "636385",
				"house_number" => "Y67",
				"street" => "Tyy",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 1,
				"created_at" => "2023-05-11 09:33:02",
				"updated_at" => "2023-05-11 09:33:14",
			],
			[
				"id" => 14,
				"name" => NULL,
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "03111241872",
				"house_number" => "SS/10",
				"street" => "Defence view phase 2",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 1,
				"created_at" => "2023-05-12 03:07:47",
				"updated_at" => "2023-05-12 03:13:39",
			],
			[
				"id" => 15,
				"name" => NULL,
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "123456",
				"house_number" => "Ss10",
				"street" => "Defence",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 1,
				"created_at" => "2023-05-17 03:23:00",
				"updated_at" => "2023-05-17 03:23:09",
			],
			[
				"id" => 16,
				"name" => NULL,
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "2356895623",
				"house_number" => "SS/10",
				"street" => "Defense",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 1,
				"created_at" => "2023-05-31 09:32:42",
				"updated_at" => "2023-05-31 09:32:50",
			],
			[
				"id" => 17,
				"name" => NULL,
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "123456789",
				"house_number" => "SS/10",
				"street" => "Defense view",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 1,
				"created_at" => "2023-05-31 10:09:14",
				"updated_at" => "2023-05-31 10:09:20",
			],
			[
				"id" => 18,
				"name" => NULL,
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "12345678",
				"house_number" => "SS/10",
				"street" => "Defense view",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 1,
				"created_at" => "2023-05-31 10:11:24",
				"updated_at" => "2023-05-31 10:11:31",
			],
			[
				"id" => 19,
				"name" => NULL,
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "12345612345",
				"house_number" => "SS/10",
				"street" => "Defense",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 1,
				"created_at" => "2023-05-31 10:16:49",
				"updated_at" => "2023-05-31 10:16:56",
			],
			[
				"id" => 20,
				"name" => NULL,
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "1234568",
				"house_number" => "SS/10",
				"street" => "Defense",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 1,
				"created_at" => "2023-05-31 10:36:34",
				"updated_at" => "2023-05-31 10:36:41",
			],
			[
				"id" => 21,
				"name" => NULL,
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "123456781",
				"house_number" => "SS/10",
				"street" => "Defense view",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 1,
				"created_at" => "2023-05-31 10:40:51",
				"updated_at" => "2023-05-31 10:41:01",
			],
			[
				"id" => 22,
				"name" => NULL,
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "1234567892",
				"house_number" => "D-10",
				"street" => "Michigan avenue",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 1,
				"created_at" => "2023-05-31 10:46:40",
				"updated_at" => "2023-05-31 10:46:47",
			],
			[
				"id" => 23,
				"name" => NULL,
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "66666",
				"house_number" => "Gh",
				"street" => "Vh",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 0,
				"created_at" => "2023-06-13 08:36:03",
				"updated_at" => "2023-06-13 08:36:03",
			],
			[
				"id" => 24,
				"name" => NULL,
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "55",
				"house_number" => "Vhh",
				"street" => "Ggg",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 0,
				"created_at" => "2023-06-13 08:48:03",
				"updated_at" => "2023-06-13 08:48:03",
			],
			[
				"id" => 25,
				"name" => NULL,
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "12345678923",
				"house_number" => "Ghuy",
				"street" => "TT Ryi",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 1,
				"created_at" => "2023-06-13 11:39:49",
				"updated_at" => "2023-06-13 11:47:09",
			],
			[
				"id" => 26,
				"name" => NULL,
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "535532",
				"house_number" => "Gy",
				"street" => "Gg",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 1,
				"created_at" => "2023-06-13 11:57:07",
				"updated_at" => "2023-06-13 11:58:40",
			],
			[
				"id" => 27,
				"name" => NULL,
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "23568923",
				"house_number" => "Yy",
				"street" => "6u",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 1,
				"created_at" => "2023-06-13 12:39:38",
				"updated_at" => "2023-06-13 12:39:43",
			],
			[
				"id" => 30,
				"name" => NULL,
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "03351207068",
				"house_number" => "Ss10",
				"street" => "Defense",
				"address" => NULL,
				"email" => NULL,
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 1,
				"created_at" => "2023-08-26 09:23:17",
				"updated_at" => "2023-09-05 00:34:04",
			],
			[
				"id" => 31,
				"name" => "Sohail Asghar",
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "03083500720",
				"house_number" => NULL,
				"street" => NULL,
				"address" => NULL,
				"email" => "sohailasghar236@dispostable.com",
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 0,
				"created_at" => "2023-09-27 09:44:05",
				"updated_at" => "2023-09-27 09:44:05",
			],
			[
				"id" => 32,
				"name" => "Sohail Asghar",
				"service_location" => NULL,
				"geo_location" => NULL,
				"phone_number" => "03128617021",
				"house_number" => "House no. G-33",
				"street" => "Mari Petroleum Company",
				"address" => "Daharki District Ghotki",
				"email" => "sohailasghar239@hotmail.com",
				"email_verified_at" => NULL,
				"pin" => NULL,
				"remember_token" => NULL,
				"verified_customer" => 0,
				"created_at" => "2023-09-28 12:00:51",
				"updated_at" => "2023-09-28 12:00:51",
			],
		];

		// Insert data into the customers table
		Customer::insert($customers);
	}
}
