<?php

namespace Database\Seeders;

use App\Models\OrderDealOption;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class OrderDealOptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        OrderDealOption::truncate();

        $orderDealOptions = array(
            array(
                "id" => 1,
                "deal_id" => 74,
                "order_master_id" => 1,
                "order_detail_id" => 1,
                "item_id" => 11,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 2,
                "deal_id" => 74,
                "order_master_id" => 1,
                "order_detail_id" => 1,
                "item_id" => 12,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 3,
                "deal_id" => 74,
                "order_master_id" => 1,
                "order_detail_id" => 1,
                "item_id" => 14,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 4,
                "deal_id" => 70,
                "order_master_id" => 2,
                "order_detail_id" => 5,
                "item_id" => 8,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 5,
                "deal_id" => 70,
                "order_master_id" => 2,
                "order_detail_id" => 5,
                "item_id" => 9,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 6,
                "deal_id" => 70,
                "order_master_id" => 2,
                "order_detail_id" => 5,
                "item_id" => 10,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 7,
                "deal_id" => 66,
                "order_master_id" => 2,
                "order_detail_id" => 6,
                "item_id" => 1,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 8,
                "deal_id" => 66,
                "order_master_id" => 2,
                "order_detail_id" => 6,
                "item_id" => 2,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 9,
                "deal_id" => 66,
                "order_master_id" => 2,
                "order_detail_id" => 6,
                "item_id" => 3,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 10,
                "deal_id" => 74,
                "order_master_id" => 2,
                "order_detail_id" => 7,
                "item_id" => 11,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 11,
                "deal_id" => 74,
                "order_master_id" => 2,
                "order_detail_id" => 7,
                "item_id" => 11,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 12,
                "deal_id" => 74,
                "order_master_id" => 2,
                "order_detail_id" => 7,
                "item_id" => 14,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 13,
                "deal_id" => 74,
                "order_master_id" => 3,
                "order_detail_id" => 9,
                "item_id" => 11,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 14,
                "deal_id" => 74,
                "order_master_id" => 3,
                "order_detail_id" => 9,
                "item_id" => 12,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 15,
                "deal_id" => 74,
                "order_master_id" => 3,
                "order_detail_id" => 9,
                "item_id" => 15,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 16,
                "deal_id" => 74,
                "order_master_id" => 69,
                "order_detail_id" => 11,
                "item_id" => 11,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 17,
                "deal_id" => 74,
                "order_master_id" => 69,
                "order_detail_id" => 11,
                "item_id" => 13,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 18,
                "deal_id" => 74,
                "order_master_id" => 69,
                "order_detail_id" => 11,
                "item_id" => 14,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 19,
                "deal_id" => 78,
                "order_master_id" => 70,
                "order_detail_id" => 15,
                "item_id" => 21,
                "item_name" => "Chicken Tikka Pizza",
                "item_description" => "Yummy, delicious and spicy.",
                "item_image" => "/images/branch-products/1/1689944056.jpg",
                "item_original_price" => 350,
                "deal_price" => 360,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 20,
                "deal_id" => 78,
                "order_master_id" => 70,
                "order_detail_id" => 15,
                "item_id" => 22,
                "item_name" => "Arabian Ranch Pizza",
                "item_description" => "Very delicious pizza.",
                "item_image" => "/images/branch-products/1/1689945859.jpg",
                "item_original_price" => 450,
                "deal_price" => 460,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 21,
                "deal_id" => 78,
                "order_master_id" => 70,
                "order_detail_id" => 15,
                "item_id" => 24,
                "item_name" => "Pepsi",
                "item_description" => "Pesi can",
                "item_image" => "/images/branch-products/1/1689860173.png",
                "item_original_price" => 70,
                "deal_price" => 110,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 22,
                "deal_id" => 74,
                "order_master_id" => 70,
                "order_detail_id" => 16,
                "item_id" => 13,
                "item_name" => "Shawrama Pizza",
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 350,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 23,
                "deal_id" => 74,
                "order_master_id" => 70,
                "order_detail_id" => 16,
                "item_id" => 12,
                "item_name" => "Arabian Ranch Pizza",
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 450,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 24,
                "deal_id" => 74,
                "order_master_id" => 70,
                "order_detail_id" => 16,
                "item_id" => 14,
                "item_name" => "Pepsi",
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 120,
                "quantity" => 0,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 25,
                "deal_id" => 78,
                "order_master_id" => 71,
                "order_detail_id" => 134,
                "item_id" => 21,
                "item_name" => "Chicken Tikka Pizza",
                "item_description" => "Yummy, delicious and spicy.",
                "item_image" => "/images/branch-products/1/1689944056.jpg",
                "item_original_price" => 350,
                "deal_price" => 360,
                "quantity" => 0,
                "created_at" => "2023-08-16 09:06:41",
                "updated_at" => "2023-08-16 09:06:41",
            ),
            array(
                "id" => 26,
                "deal_id" => 78,
                "order_master_id" => 71,
                "order_detail_id" => 134,
                "item_id" => 22,
                "item_name" => "Arabian Ranch Pizza",
                "item_description" => "Very delicious pizza.",
                "item_image" => "/images/branch-products/1/1689945859.jpg",
                "item_original_price" => 450,
                "deal_price" => 460,
                "quantity" => 0,
                "created_at" => "2023-08-16 09:06:41",
                "updated_at" => "2023-08-16 09:06:41",
            ),
            array(
                "id" => 27,
                "deal_id" => 78,
                "order_master_id" => 71,
                "order_detail_id" => 134,
                "item_id" => 24,
                "item_name" => "Pepsi",
                "item_description" => "Pesi can",
                "item_image" => "/images/branch-products/1/1689860173.png",
                "item_original_price" => 70,
                "deal_price" => 110,
                "quantity" => 0,
                "created_at" => "2023-08-16 09:06:41",
                "updated_at" => "2023-08-16 09:06:41",
            ),
            array(
                "id" => 28,
                "deal_id" => 74,
                "order_master_id" => 71,
                "order_detail_id" => 135,
                "item_id" => 11,
                "item_name" => "Chicken Tikka Pizza",
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 350,
                "deal_price" => 400,
                "quantity" => 0,
                "created_at" => "2023-08-16 09:06:41",
                "updated_at" => "2023-08-16 09:06:41",
            ),
            array(
                "id" => 29,
                "deal_id" => 74,
                "order_master_id" => 71,
                "order_detail_id" => 135,
                "item_id" => 12,
                "item_name" => "Arabian Ranch Pizza",
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 450,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => "2023-08-16 09:06:41",
                "updated_at" => "2023-08-16 09:06:41",
            ),
            array(
                "id" => 30,
                "deal_id" => 74,
                "order_master_id" => 71,
                "order_detail_id" => 135,
                "item_id" => 14,
                "item_name" => "Pepsi",
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 120,
                "quantity" => 0,
                "created_at" => "2023-08-16 09:06:41",
                "updated_at" => "2023-08-16 09:06:41",
            ),
            array(
                "id" => 31,
                "deal_id" => 74,
                "order_master_id" => 72,
                "order_detail_id" => 136,
                "item_id" => 279,
                "item_name" => "Chicken Tikka Pizza",
                "item_description" => "Yummy, delicious and spicy.",
                "item_image" => "/images/branch-products/1/1689944056.jpg",
                "item_original_price" => 350,
                "deal_price" => 400,
                "quantity" => 0,
                "created_at" => "2023-08-16 11:32:51",
                "updated_at" => "2023-08-16 11:32:51",
            ),
            array(
                "id" => 32,
                "deal_id" => 74,
                "order_master_id" => 72,
                "order_detail_id" => 136,
                "item_id" => 282,
                "item_name" => "Shawrama Pizza",
                "item_description" => "Yummy and delicious pizza",
                "item_image" => "/images/branch-products/1/1691414759.jpg",
                "item_original_price" => 350,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => "2023-08-16 11:32:51",
                "updated_at" => "2023-08-16 11:32:51",
            ),
            array(
                "id" => 33,
                "deal_id" => 74,
                "order_master_id" => 72,
                "order_detail_id" => 136,
                "item_id" => 14,
                "item_name" => "Pepsi",
                "item_description" => "Pesi can",
                "item_image" => "/images/branch-products/1/1689860173.png",
                "item_original_price" => 70,
                "deal_price" => 120,
                "quantity" => 0,
                "created_at" => "2023-08-16 11:32:51",
                "updated_at" => "2023-08-16 11:32:51",
            ),
            array(
                "id" => 34,
                "deal_id" => 78,
                "order_master_id" => 72,
                "order_detail_id" => 137,
                "item_id" => 279,
                "item_name" => "Chicken Tikka Pizza",
                "item_description" => "Yummy, delicious and spicy.",
                "item_image" => "/images/branch-products/1/1689944056.jpg",
                "item_original_price" => 350,
                "deal_price" => 360,
                "quantity" => 0,
                "created_at" => "2023-08-16 11:32:51",
                "updated_at" => "2023-08-16 11:32:51",
            ),
            array(
                "id" => 35,
                "deal_id" => 78,
                "order_master_id" => 72,
                "order_detail_id" => 137,
                "item_id" => 279,
                "item_name" => "Chicken Tikka Pizza",
                "item_description" => "Yummy, delicious and spicy.",
                "item_image" => "/images/branch-products/1/1689944056.jpg",
                "item_original_price" => 350,
                "deal_price" => 360,
                "quantity" => 0,
                "created_at" => "2023-08-16 11:32:51",
                "updated_at" => "2023-08-16 11:32:51",
            ),
            array(
                "id" => 36,
                "deal_id" => 78,
                "order_master_id" => 72,
                "order_detail_id" => 137,
                "item_id" => 24,
                "item_name" => "Pepsi",
                "item_description" => "Pesi can",
                "item_image" => "/images/branch-products/1/1689860173.png",
                "item_original_price" => 70,
                "deal_price" => 110,
                "quantity" => 0,
                "created_at" => "2023-08-16 11:32:51",
                "updated_at" => "2023-08-16 11:32:51",
            ),
            array(
                "id" => 37,
                "deal_id" => 70,
                "order_master_id" => 72,
                "order_detail_id" => 138,
                "item_id" => 280,
                "item_name" => "Arabian Ranch Pizza",
                "item_description" => "Very delicious pizza.",
                "item_image" => "/images/branch-products/1/1689945859.jpg",
                "item_original_price" => 450,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => "2023-08-16 11:32:51",
                "updated_at" => "2023-08-16 11:32:51",
            ),
            array(
                "id" => 38,
                "deal_id" => 70,
                "order_master_id" => 72,
                "order_detail_id" => 138,
                "item_id" => 279,
                "item_name" => "Chicken Tikka Pizza",
                "item_description" => "Yummy, delicious and spicy.",
                "item_image" => "/images/branch-products/1/1689944056.jpg",
                "item_original_price" => 350,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => "2023-08-16 11:32:51",
                "updated_at" => "2023-08-16 11:32:51",
            ),
            array(
                "id" => 39,
                "deal_id" => 70,
                "order_master_id" => 72,
                "order_detail_id" => 138,
                "item_id" => 10,
                "item_name" => "Latte",
                "item_description" => "Delicious latte with cream",
                "item_image" => "/images/branch-products/1/1691399932.webp",
                "item_original_price" => 400,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => "2023-08-16 11:32:51",
                "updated_at" => "2023-08-16 11:32:51",
            ),
            array(
                "id" => 40,
                "deal_id" => 66,
                "order_master_id" => 72,
                "order_detail_id" => 139,
                "item_id" => 1,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => "2023-08-16 11:32:51",
                "updated_at" => "2023-08-16 11:32:51",
            ),
            array(
                "id" => 41,
                "deal_id" => 66,
                "order_master_id" => 72,
                "order_detail_id" => 139,
                "item_id" => 1,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => "2023-08-16 11:32:51",
                "updated_at" => "2023-08-16 11:32:51",
            ),
            array(
                "id" => 42,
                "deal_id" => 66,
                "order_master_id" => 72,
                "order_detail_id" => 139,
                "item_id" => 3,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => "2023-08-16 11:32:51",
                "updated_at" => "2023-08-16 11:32:51",
            ),
            array(
                "id" => 43,
                "deal_id" => 78,
                "order_master_id" => 73,
                "order_detail_id" => 143,
                "item_id" => 279,
                "item_name" => "Chicken Tikka Pizza",
                "item_description" => "Yummy, delicious and spicy.",
                "item_image" => "/images/branch-products/1/1689944056.jpg",
                "item_original_price" => 350,
                "deal_price" => 360,
                "quantity" => 0,
                "created_at" => "2023-08-24 21:33:39",
                "updated_at" => "2023-08-24 21:33:39",
            ),
            array(
                "id" => 44,
                "deal_id" => 78,
                "order_master_id" => 73,
                "order_detail_id" => 143,
                "item_id" => 282,
                "item_name" => "Shawrama Pizza",
                "item_description" => "Yummy and delicious pizza",
                "item_image" => "/images/branch-products/1/1691414759.jpg",
                "item_original_price" => 350,
                "deal_price" => 360,
                "quantity" => 0,
                "created_at" => "2023-08-24 21:33:39",
                "updated_at" => "2023-08-24 21:33:39",
            ),
            array(
                "id" => 45,
                "deal_id" => 78,
                "order_master_id" => 73,
                "order_detail_id" => 143,
                "item_id" => 277,
                "item_name" => "Pepsi",
                "item_description" => "Pesi can",
                "item_image" => "/images/branch-products/1/1689860173.png",
                "item_original_price" => 70,
                "deal_price" => 110,
                "quantity" => 0,
                "created_at" => "2023-08-24 21:33:39",
                "updated_at" => "2023-08-24 21:33:39",
            ),
            array(
                "id" => 46,
                "deal_id" => 77,
                "order_master_id" => 74,
                "order_detail_id" => 146,
                "item_id" => 279,
                "item_name" => "Chicken Tikka Pizza",
                "item_description" => "Yummy, delicious and spicy.",
                "item_image" => "/images/branch-products/1/1689944056.jpg",
                "item_original_price" => 350,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => "2023-08-25 05:24:21",
                "updated_at" => "2023-08-25 05:24:21",
            ),
            array(
                "id" => 47,
                "deal_id" => 77,
                "order_master_id" => 74,
                "order_detail_id" => 146,
                "item_id" => 280,
                "item_name" => "Arabian Ranch Pizza",
                "item_description" => "Very delicious pizza.",
                "item_image" => "/images/branch-products/1/1689945859.jpg",
                "item_original_price" => 450,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => "2023-08-25 05:24:21",
                "updated_at" => "2023-08-25 05:24:21",
            ),
            array(
                "id" => 48,
                "deal_id" => 77,
                "order_master_id" => 74,
                "order_detail_id" => 146,
                "item_id" => 277,
                "item_name" => "Pepsi",
                "item_description" => "Pesi can",
                "item_image" => "/images/branch-products/1/1689860173.png",
                "item_original_price" => 70,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => "2023-08-25 05:24:21",
                "updated_at" => "2023-08-25 05:24:21",
            ),
            array(
                "id" => 49,
                "deal_id" => 78,
                "order_master_id" => 75,
                "order_detail_id" => 148,
                "item_id" => 279,
                "item_name" => "Chicken Tikka Pizza",
                "item_description" => "Yummy, delicious and spicy.",
                "item_image" => "/images/branch-products/1/1689944056.jpg",
                "item_original_price" => 350,
                "deal_price" => 360,
                "quantity" => 0,
                "created_at" => "2023-08-25 11:29:32",
                "updated_at" => "2023-08-25 11:29:32",
            ),
            array(
                "id" => 50,
                "deal_id" => 78,
                "order_master_id" => 75,
                "order_detail_id" => 148,
                "item_id" => 280,
                "item_name" => "Arabian Ranch Pizza",
                "item_description" => "Very delicious pizza.",
                "item_image" => "/images/branch-products/1/1689945859.jpg",
                "item_original_price" => 450,
                "deal_price" => 460,
                "quantity" => 0,
                "created_at" => "2023-08-25 11:29:32",
                "updated_at" => "2023-08-25 11:29:32",
            ),
            array(
                "id" => 51,
                "deal_id" => 78,
                "order_master_id" => 75,
                "order_detail_id" => 148,
                "item_id" => 277,
                "item_name" => "Pepsi",
                "item_description" => "Pesi can",
                "item_image" => "/images/branch-products/1/1689860173.png",
                "item_original_price" => 70,
                "deal_price" => 110,
                "quantity" => 0,
                "created_at" => "2023-08-25 11:29:32",
                "updated_at" => "2023-08-25 11:29:32",
            ),
            array(
                "id" => 52,
                "deal_id" => 78,
                "order_master_id" => 80,
                "order_detail_id" => 155,
                "item_id" => 21,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 360,
                "quantity" => 0,
                "created_at" => "2023-08-28 07:34:24",
                "updated_at" => "2023-08-28 07:34:24",
            ),
            array(
                "id" => 53,
                "deal_id" => 78,
                "order_master_id" => 80,
                "order_detail_id" => 155,
                "item_id" => 22,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 460,
                "quantity" => 0,
                "created_at" => "2023-08-28 07:34:24",
                "updated_at" => "2023-08-28 07:34:24",
            ),
            array(
                "id" => 54,
                "deal_id" => 78,
                "order_master_id" => 80,
                "order_detail_id" => 155,
                "item_id" => 24,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 110,
                "quantity" => 0,
                "created_at" => "2023-08-28 07:34:24",
                "updated_at" => "2023-08-28 07:34:24",
            ),
            array(
                "id" => 55,
                "deal_id" => 78,
                "order_master_id" => 82,
                "order_detail_id" => 157,
                "item_id" => 21,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 360,
                "quantity" => 0,
                "created_at" => "2023-08-28 07:49:50",
                "updated_at" => "2023-08-28 07:49:50",
            ),
            array(
                "id" => 56,
                "deal_id" => 78,
                "order_master_id" => 82,
                "order_detail_id" => 157,
                "item_id" => 21,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 360,
                "quantity" => 0,
                "created_at" => "2023-08-28 07:49:50",
                "updated_at" => "2023-08-28 07:49:50",
            ),
            array(
                "id" => 57,
                "deal_id" => 78,
                "order_master_id" => 82,
                "order_detail_id" => 157,
                "item_id" => 24,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 110,
                "quantity" => 0,
                "created_at" => "2023-08-28 07:49:50",
                "updated_at" => "2023-08-28 07:49:50",
            ),
            array(
                "id" => 58,
                "deal_id" => 78,
                "order_master_id" => 83,
                "order_detail_id" => 158,
                "item_id" => 21,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 360,
                "quantity" => 0,
                "created_at" => "2023-08-28 08:02:24",
                "updated_at" => "2023-08-28 08:02:24",
            ),
            array(
                "id" => 59,
                "deal_id" => 78,
                "order_master_id" => 83,
                "order_detail_id" => 158,
                "item_id" => 21,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 360,
                "quantity" => 0,
                "created_at" => "2023-08-28 08:02:24",
                "updated_at" => "2023-08-28 08:02:24",
            ),
            array(
                "id" => 60,
                "deal_id" => 78,
                "order_master_id" => 83,
                "order_detail_id" => 158,
                "item_id" => 24,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 110,
                "quantity" => 0,
                "created_at" => "2023-08-28 08:02:24",
                "updated_at" => "2023-08-28 08:02:24",
            ),
            array(
                "id" => 61,
                "deal_id" => 78,
                "order_master_id" => 84,
                "order_detail_id" => 159,
                "item_id" => 21,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 360,
                "quantity" => 0,
                "created_at" => "2023-08-28 08:06:14",
                "updated_at" => "2023-08-28 08:06:14",
            ),
            array(
                "id" => 62,
                "deal_id" => 78,
                "order_master_id" => 84,
                "order_detail_id" => 159,
                "item_id" => 21,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 360,
                "quantity" => 0,
                "created_at" => "2023-08-28 08:06:14",
                "updated_at" => "2023-08-28 08:06:14",
            ),
            array(
                "id" => 63,
                "deal_id" => 78,
                "order_master_id" => 84,
                "order_detail_id" => 159,
                "item_id" => 24,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 110,
                "quantity" => 0,
                "created_at" => "2023-08-28 08:06:14",
                "updated_at" => "2023-08-28 08:06:14",
            ),
            array(
                "id" => 64,
                "deal_id" => 78,
                "order_master_id" => 86,
                "order_detail_id" => 161,
                "item_id" => 21,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 360,
                "quantity" => 0,
                "created_at" => "2023-08-28 12:31:44",
                "updated_at" => "2023-08-28 12:31:44",
            ),
            array(
                "id" => 65,
                "deal_id" => 78,
                "order_master_id" => 86,
                "order_detail_id" => 161,
                "item_id" => 21,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 360,
                "quantity" => 0,
                "created_at" => "2023-08-28 12:31:44",
                "updated_at" => "2023-08-28 12:31:44",
            ),
            array(
                "id" => 66,
                "deal_id" => 78,
                "order_master_id" => 86,
                "order_detail_id" => 161,
                "item_id" => 24,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 110,
                "quantity" => 0,
                "created_at" => "2023-08-28 12:31:44",
                "updated_at" => "2023-08-28 12:31:44",
            ),
            array(
                "id" => 67,
                "deal_id" => 78,
                "order_master_id" => 87,
                "order_detail_id" => 162,
                "item_id" => 21,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 360,
                "quantity" => 0,
                "created_at" => "2023-08-29 06:20:15",
                "updated_at" => "2023-08-29 06:20:15",
            ),
            array(
                "id" => 68,
                "deal_id" => 78,
                "order_master_id" => 87,
                "order_detail_id" => 162,
                "item_id" => 21,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 360,
                "quantity" => 0,
                "created_at" => "2023-08-29 06:20:15",
                "updated_at" => "2023-08-29 06:20:15",
            ),
            array(
                "id" => 69,
                "deal_id" => 78,
                "order_master_id" => 87,
                "order_detail_id" => 162,
                "item_id" => 24,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 110,
                "quantity" => 0,
                "created_at" => "2023-08-29 06:20:15",
                "updated_at" => "2023-08-29 06:20:15",
            ),
            array(
                "id" => 70,
                "deal_id" => 78,
                "order_master_id" => 90,
                "order_detail_id" => 165,
                "item_id" => 22,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 460,
                "quantity" => 0,
                "created_at" => "2023-08-29 06:24:23",
                "updated_at" => "2023-08-29 06:24:23",
            ),
            array(
                "id" => 71,
                "deal_id" => 78,
                "order_master_id" => 90,
                "order_detail_id" => 165,
                "item_id" => 23,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 360,
                "quantity" => 0,
                "created_at" => "2023-08-29 06:24:23",
                "updated_at" => "2023-08-29 06:24:23",
            ),
            array(
                "id" => 72,
                "deal_id" => 78,
                "order_master_id" => 90,
                "order_detail_id" => 165,
                "item_id" => 25,
                "item_name" => NULL,
                "item_description" => NULL,
                "item_image" => NULL,
                "item_original_price" => 0,
                "deal_price" => 110,
                "quantity" => 0,
                "created_at" => "2023-08-29 06:24:23",
                "updated_at" => "2023-08-29 06:24:23",
            ),
            array(
                "id" => 73,
                "deal_id" => 78,
                "order_master_id" => 92,
                "order_detail_id" => 167,
                "item_id" => 21,
                "item_name" => "Chicken Tikka Pizza",
                "item_description" => "Yummy, delicious and spicy.",
                "item_image" => "/images/branch-products/1/1689944056.jpg",
                "item_original_price" => 350,
                "deal_price" => 360,
                "quantity" => 0,
                "created_at" => "2023-09-04 06:41:57",
                "updated_at" => "2023-09-04 06:41:57",
            ),
            array(
                "id" => 74,
                "deal_id" => 78,
                "order_master_id" => 92,
                "order_detail_id" => 167,
                "item_id" => 21,
                "item_name" => "Chicken Tikka Pizza",
                "item_description" => "Yummy, delicious and spicy.",
                "item_image" => "/images/branch-products/1/1689944056.jpg",
                "item_original_price" => 350,
                "deal_price" => 360,
                "quantity" => 0,
                "created_at" => "2023-09-04 06:41:57",
                "updated_at" => "2023-09-04 06:41:57",
            ),
            array(
                "id" => 75,
                "deal_id" => 78,
                "order_master_id" => 92,
                "order_detail_id" => 167,
                "item_id" => 24,
                "item_name" => "Pepsi",
                "item_description" => "Pesi can",
                "item_image" => "/images/branch-products/1/1689860173.png",
                "item_original_price" => 70,
                "deal_price" => 110,
                "quantity" => 0,
                "created_at" => "2023-09-04 06:41:57",
                "updated_at" => "2023-09-04 06:41:57",
            ),
            array(
                "id" => 76,
                "deal_id" => 78,
                "order_master_id" => 93,
                "order_detail_id" => 168,
                "item_id" => 21,
                "item_name" => "Chicken Tikka Pizza",
                "item_description" => "Yummy, delicious and spicy.",
                "item_image" => "/images/branch-products/1/1689944056.jpg",
                "item_original_price" => 350,
                "deal_price" => 360,
                "quantity" => 0,
                "created_at" => "2023-09-04 07:15:20",
                "updated_at" => "2023-09-04 07:15:20",
            ),
            array(
                "id" => 77,
                "deal_id" => 78,
                "order_master_id" => 93,
                "order_detail_id" => 168,
                "item_id" => 21,
                "item_name" => "Chicken Tikka Pizza",
                "item_description" => "Yummy, delicious and spicy.",
                "item_image" => "/images/branch-products/1/1689944056.jpg",
                "item_original_price" => 350,
                "deal_price" => 360,
                "quantity" => 0,
                "created_at" => "2023-09-04 07:15:20",
                "updated_at" => "2023-09-04 07:15:20",
            ),
            array(
                "id" => 78,
                "deal_id" => 78,
                "order_master_id" => 93,
                "order_detail_id" => 168,
                "item_id" => 24,
                "item_name" => "Pepsi",
                "item_description" => "Pesi can",
                "item_image" => "/images/branch-products/1/1689860173.png",
                "item_original_price" => 70,
                "deal_price" => 110,
                "quantity" => 0,
                "created_at" => "2023-09-04 07:15:20",
                "updated_at" => "2023-09-04 07:15:20",
            ),
            array(
                "id" => 86,
                "deal_id" => 77,
                "order_master_id" => 97,
                "order_detail_id" => 182,
                "item_id" => 282,
                "item_name" => "Shawrama Pizza",
                "item_description" => "Yummy and delicious pizza",
                "item_image" => "/images/branch-products/1/1691414759.jpg",
                "item_original_price" => 350,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => "2023-09-27 12:12:04",
                "updated_at" => "2023-09-27 12:12:04",
            ),
            array(
                "id" => 87,
                "deal_id" => 77,
                "order_master_id" => 97,
                "order_detail_id" => 182,
                "item_id" => 282,
                "item_name" => "Shawrama Pizza",
                "item_description" => "Yummy and delicious pizza",
                "item_image" => "/images/branch-products/1/1691414759.jpg",
                "item_original_price" => 350,
                "deal_price" => 0,
                "quantity" => 0,
                "created_at" => "2023-09-27 12:12:04",
                "updated_at" => "2023-09-27 12:12:04",
            ),
            array(
                "id" => 97,
                "deal_id" => 74,
                "order_master_id" => 101,
                "order_detail_id" => 191,
                "item_id" => 279,
                "item_name" => "Chicken Tikka Pizza",
                "item_description" => "Yummy, delicious and spicy.",
                "item_image" => "/images/branch-products/1/1689944056.jpg",
                "item_original_price" => 350,
                "deal_price" => 400,
                "quantity" => 0,
                "created_at" => "2023-09-27 12:20:51",
                "updated_at" => "2023-09-27 12:20:51",
            ),
            array(
                "id" => 98,
                "deal_id" => 74,
                "order_master_id" => 101,
                "order_detail_id" => 191,
                "item_id" => 279,
                "item_name" => "Chicken Tikka Pizza",
                "item_description" => "Yummy, delicious and spicy.",
                "item_image" => "/images/branch-products/1/1689944056.jpg",
                "item_original_price" => 350,
                "deal_price" => 400,
                "quantity" => 0,
                "created_at" => "2023-09-27 12:20:51",
                "updated_at" => "2023-09-27 12:20:51",
            ),
            array(
                "id" => 99,
                "deal_id" => 74,
                "order_master_id" => 101,
                "order_detail_id" => 191,
                "item_id" => 277,
                "item_name" => "Pepsi",
                "item_description" => "Pesi can",
                "item_image" => "/images/branch-products/1/1689860173.png",
                "item_original_price" => 70,
                "deal_price" => 120,
                "quantity" => 0,
                "created_at" => "2023-09-27 12:20:51",
                "updated_at" => "2023-09-27 12:20:51",
            ),
        );

        OrderDealOption::insert($orderDealOptions);
    }
}
