<?php

namespace Database\Seeders;

use App\Models\OrderMaster;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class OrderMasterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        OrderMaster::truncate();

        $orders = array(
            array(
                "id" => 67,
                "customer_id" => "7",
                "branch_id" => 1,
                "item_quantity" => 5,
                "grand_total" => 8160.00,
                "status" => 0,
                "order_type" => NULL,
                "created_at" => "2023-08-10 11:47:52",
                "updated_at" => "2023-08-10 11:47:52",
            ),
            array(
                "id" => 68,
                "customer_id" => "7",
                "branch_id" => 1,
                "item_quantity" => 2,
                "grand_total" => 2520.00,
                "status" => 0,
                "order_type" => NULL,
                "created_at" => "2023-08-11 06:36:18",
                "updated_at" => "2023-08-11 06:36:18",
            ),
            array(
                "id" => 69,
                "customer_id" => "7",
                "branch_id" => 1,
                "item_quantity" => 2,
                "grand_total" => 2760.00,
                "status" => 0,
                "order_type" => NULL,
                "created_at" => "2023-08-11 14:29:32",
                "updated_at" => "2023-08-11 14:29:32",
            ),
            array(
                "id" => 71,
                "customer_id" => "9",
                "branch_id" => 1,
                "item_quantity" => 2,
                "grand_total" => 7200.00,
                "status" => 0,
                "order_type" => NULL,
                "created_at" => "2023-08-16 09:06:41",
                "updated_at" => "2023-08-16 09:06:41",
            ),
            array(
                "id" => 72,
                "customer_id" => "7",
                "branch_id" => 1,
                "item_quantity" => 3,
                "grand_total" => 10100.00,
                "status" => 0,
                "order_type" => NULL,
                "created_at" => "2023-08-16 11:32:51",
                "updated_at" => "2023-08-16 11:32:51",
            ),
            array(
                "id" => 73,
                "customer_id" => "3",
                "branch_id" => 1,
                "item_quantity" => 4,
                "grand_total" => 4700.00,
                "status" => 0,
                "order_type" => NULL,
                "created_at" => "2023-08-24 21:33:39",
                "updated_at" => "2023-08-24 21:33:39",
            ),
            array(
                "id" => 74,
                "customer_id" => "3",
                "branch_id" => 1,
                "item_quantity" => 4,
                "grand_total" => 4910.00,
                "status" => 0,
                "order_type" => NULL,
                "created_at" => "2023-08-25 05:24:21",
                "updated_at" => "2023-08-25 05:24:21",
            ),
            array(
                "id" => 75,
                "customer_id" => "5",
                "branch_id" => 1,
                "item_quantity" => 1,
                "grand_total" => 2400.00,
                "status" => 0,
                "order_type" => NULL,
                "created_at" => "2023-08-25 11:29:32",
                "updated_at" => "2023-08-25 11:29:32",
            ),
            array(
                "id" => 79,
                "customer_id" => "30",
                "branch_id" => 1,
                "item_quantity" => 5,
                "grand_total" => 700.00,
                "status" => 1,
                "order_type" => NULL,
                "created_at" => "2023-08-26 09:23:24",
                "updated_at" => "2023-08-26 09:23:24",
            ),
            array(
                "id" => 80,
                "customer_id" => "30",
                "branch_id" => 1,
                "item_quantity" => 4,
                "grand_total" => 7600.00,
                "status" => 1,
                "order_type" => NULL,
                "created_at" => "2023-08-28 07:34:24",
                "updated_at" => "2023-08-28 07:34:24",
            ),
            array(
                "id" => 81,
                "customer_id" => "30",
                "branch_id" => 1,
                "item_quantity" => 2,
                "grand_total" => 1100.00,
                "status" => 1,
                "order_type" => NULL,
                "created_at" => "2023-08-28 07:44:32",
                "updated_at" => "2023-08-28 07:44:32",
            ),
            array(
                "id" => 82,
                "customer_id" => "30",
                "branch_id" => 1,
                "item_quantity" => 1,
                "grand_total" => 4610.00,
                "status" => 1,
                "order_type" => NULL,
                "created_at" => "2023-08-28 07:49:50",
                "updated_at" => "2023-08-28 07:49:50",
            ),
            array(
                "id" => 83,
                "customer_id" => "30",
                "branch_id" => 1,
                "item_quantity" => 1,
                "grand_total" => 5510.00,
                "status" => 3,
                "order_type" => NULL,
                "created_at" => "2023-08-28 08:02:24",
                "updated_at" => "2023-08-28 08:02:24",
            ),
            array(
                "id" => 84,
                "customer_id" => "30",
                "branch_id" => 1,
                "item_quantity" => 1,
                "grand_total" => 5510.00,
                "status" => 1,
                "order_type" => NULL,
                "created_at" => "2023-08-28 08:06:14",
                "updated_at" => "2023-08-28 08:06:14",
            ),
            array(
                "id" => 86,
                "customer_id" => "30",
                "branch_id" => 1,
                "item_quantity" => 3,
                "grand_total" => 6129.00,
                "status" => 1,
                "order_type" => NULL,
                "created_at" => "2023-08-28 12:31:44",
                "updated_at" => "2023-08-28 12:31:44",
            ),
            array(
                "id" => 87,
                "customer_id" => "30",
                "branch_id" => 1,
                "item_quantity" => 1,
                "grand_total" => 4010.00,
                "status" => 1,
                "order_type" => NULL,
                "created_at" => "2023-08-29 06:20:15",
                "updated_at" => "2023-08-29 06:20:15",
            ),
            array(
                "id" => 88,
                "customer_id" => "30",
                "branch_id" => 1,
                "item_quantity" => 1,
                "grand_total" => 150.00,
                "status" => 0,
                "order_type" => NULL,
                "created_at" => "2023-08-29 06:23:10",
                "updated_at" => "2023-08-29 06:23:10",
            ),
            array(
                "id" => 89,
                "customer_id" => "30",
                "branch_id" => 1,
                "item_quantity" => 1,
                "grand_total" => 788.00,
                "status" => 0,
                "order_type" => NULL,
                "created_at" => "2023-08-29 06:23:39",
                "updated_at" => "2023-08-29 06:23:39",
            ),
            array(
                "id" => 90,
                "customer_id" => "30",
                "branch_id" => 1,
                "item_quantity" => 1,
                "grand_total" => 5010.00,
                "status" => 0,
                "order_type" => NULL,
                "created_at" => "2023-08-29 06:24:23",
                "updated_at" => "2023-08-29 06:24:23",
            ),
            array(
                "id" => 91,
                "customer_id" => "30",
                "branch_id" => 1,
                "item_quantity" => 2,
                "grand_total" => 600.00,
                "status" => 0,
                "order_type" => NULL,
                "created_at" => "2023-09-01 08:10:20",
                "updated_at" => "2023-09-01 08:10:20",
            ),
            array(
                "id" => 92,
                "customer_id" => "30",
                "branch_id" => 1,
                "item_quantity" => 2,
                "grand_total" => 8920.00,
                "status" => 4,
                "order_type" => NULL,
                "created_at" => "2023-09-04 06:41:57",
                "updated_at" => "2023-09-04 09:59:51",
            ),
            array(
                "id" => 93,
                "customer_id" => "30",
                "branch_id" => 1,
                "item_quantity" => 3,
                "grand_total" => 12030.00,
                "status" => 4,
                "order_type" => NULL,
                "created_at" => "2023-09-04 07:15:20",
                "updated_at" => "2023-09-04 10:25:18",
            ),
            array(
                "id" => 94,
                "customer_id" => "30",
                "branch_id" => 1,
                "item_quantity" => 4,
                "grand_total" => 280.00,
                "status" => 4,
                "order_type" => NULL,
                "created_at" => "2023-09-04 09:30:15",
                "updated_at" => "2023-09-04 10:25:03",
            ),
            array(
                "id" => 97,
                "customer_id" => "31",
                "branch_id" => 1,
                "item_quantity" => 3,
                "grand_total" => 3219.00,
                "status" => 0,
                "order_type" => NULL,
                "created_at" => "2023-09-27 12:12:04",
                "updated_at" => "2023-09-27 12:12:04",
            ),
            array(
                "id" => 101,
                "customer_id" => "31",
                "branch_id" => 1,
                "item_quantity" => 2,
                "grand_total" => 3200.00,
                "status" => 0,
                "order_type" => NULL,
                "created_at" => "2023-09-27 12:20:51",
                "updated_at" => "2023-09-27 12:20:51",
            ),
        );

        OrderMaster::insert($orders);
    }
}
